/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bunnyrace.editor.gui;

/**
 *
 * @author mikko
 */
public class UusiEditorUI extends javax.swing.JFrame {

    /**
     * Creates new form UusiEditorUI
     */
    public UusiEditorUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        valintaButton = new javax.swing.JToggleButton();
        herneButton = new javax.swing.JToggleButton();
        mansikkaButton = new javax.swing.JToggleButton();
        pommiButton = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        poistaButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jToolBar2 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        valintaButton.setText("Valitse");
        valintaButton.setFocusable(false);
        valintaButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        valintaButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        valintaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valintaButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(valintaButton);

        herneButton.setText("Herne");
        herneButton.setFocusable(false);
        herneButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        herneButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        herneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                herneButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(herneButton);

        mansikkaButton.setText("Mansikka");
        mansikkaButton.setFocusable(false);
        mansikkaButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mansikkaButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mansikkaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mansikkaButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(mansikkaButton);

        pommiButton.setText("Pommi");
        pommiButton.setFocusable(false);
        pommiButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pommiButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pommiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pommiButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(pommiButton);
        jToolBar1.add(jSeparator1);

        poistaButton.setText("Poista");
        poistaButton.setFocusable(false);
        poistaButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        poistaButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        poistaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poistaButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(poistaButton);

        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        jLabel1.setText("Zoom:");
        jToolBar2.add(jLabel1);
        jToolBar2.add(jSlider1);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void herneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_herneButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_herneButtonActionPerformed

    private void valintaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valintaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valintaButtonActionPerformed

    private void mansikkaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mansikkaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mansikkaButtonActionPerformed

    private void pommiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pommiButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pommiButtonActionPerformed

    private void poistaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poistaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poistaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UusiEditorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UusiEditorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UusiEditorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UusiEditorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UusiEditorUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton herneButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToggleButton mansikkaButton;
    private javax.swing.JButton poistaButton;
    private javax.swing.JToggleButton pommiButton;
    private javax.swing.JToggleButton valintaButton;
    // End of variables declaration//GEN-END:variables
}
